# EJERCICIO DE CLUSTERING - JUAN LUIS GERMAN SAURA

#### CARGA DE LIBRERIAS E IMPORTACIÓN DE LOS DATOS

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv(r"C:\Users\Yannis\Downloads\genres_v2.csv")

C:\Users\Yannis\AppData\Local\Temp\ipykernel_1348\1520482952.py:1: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Yannis\Downloads\genres_v2.csv")

#### LIMPIEZA Y FILTRADO DE VARIABLES

In [48]:
display(df.shape)
display(df.head(5))
display(df.describe())
display(df.dtypes)

(42305, 10)

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,0.831,0.814,-7.364,0.4200,0.0598,0.013400,0.0556,0.3890,156.985,124539
1,0.719,0.493,-7.230,0.0794,0.4010,0.000000,0.1180,0.1240,115.080,224427
2,0.850,0.893,-4.783,0.0623,0.0138,0.000004,0.3720,0.0391,218.050,98821
3,0.476,0.781,-4.710,0.1030,0.0237,0.000000,0.1140,0.1750,186.948,123661
4,0.798,0.624,-7.668,0.2930,0.2170,0.000000,0.1660,0.5910,147.988,123298

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
count,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000
mean,0.639364,0.762516,-6.465442,0.136561,0.096160,0.283048,0.214079,0.357101,147.474056,250865.846685
std,0.156617,0.183823,2.941165,0.126168,0.170827,0.370791,0.175576,0.233200,23.844623,102957.713571
min,0.065100,0.000243,-33.357000,0.022700,0.000001,0.000000,0.010700,0.018700,57.967000,25600.000000
25%,0.524000,0.632000,-8.161000,0.049100,0.001730,0.000000,0.099600,0.161000,129.931000,179840.000000
50%,0.646000,0.803000,-6.234000,0.075500,0.016400,0.005940,0.135000,0.322000,144.973000,224760.000000
75%,0.766000,0.923000,-4.513000,0.193000,0.107000,0.722000,0.294000,0.522000,161.464000,301133.000000
max,0.988000,1.000000,3.148000,0.946000,0.988000,0.989000,0.988000,0.988000,220.290000,913052.000000

danceability        float64
energy              float64
loudness            float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
duration_ms           int64
dtype: object

In [49]:
df.isnull().sum()

danceability        0
energy              0
loudness            0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
dtype: int64

- Se eliminan song_name, unnamed y tittle por ser categóricas y por tener cerca del 50% de sus observaciones nulas
- Se eliminan id, uri	track_href, analysis_url,type por aportar poco información por ser identificadores<br>
- Se elimina genre, type y key por ser variable categórica<br>
- Se elimina time_signature por tener una std cercana a 0 dentro de su propia variable<br>

In [50]:
df = df.drop(["song_name","Unnamed: 0","title"],axis = 1)
df= df.drop(["id","uri","track_href","analysis_url","genre","type","key","time_signature","mode"],axis = 1)

KeyError: "['song_name', 'Unnamed: 0', 'title'] not found in axis"

In [ ]:
#Comprobación tras el borrado
df.head(5)

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,0.831,0.814,-7.364,0.4200,0.0598,0.013400,0.0556,0.3890,156.985,124539
1,0.719,0.493,-7.230,0.0794,0.4010,0.000000,0.1180,0.1240,115.080,224427
2,0.850,0.893,-4.783,0.0623,0.0138,0.000004,0.3720,0.0391,218.050,98821
3,0.476,0.781,-4.710,0.1030,0.0237,0.000000,0.1140,0.1750,186.948,123661
4,0.798,0.624,-7.668,0.2930,0.2170,0.000000,0.1660,0.5910,147.988,123298