### Spotify dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('genres_v2.csv')

/var/folders/zt/nr4slqvn18j6z9rshfmngv300000gn/T/ipykernel_13360/4018727902.py:1: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('genres_v2.csv')

Describimos el dataset y contamos nulos.

In [3]:
display(df.head())

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,...,id,uri,track_href,analysis_url,duration_ms,time_signature,genre,song_name,Unnamed: 0,title
0,0.831,0.814,2,-7.364,1,0.4200,0.0598,0.013400,0.0556,0.3890,...,2Vc6NJ9PW9gD9q343XFRKx,spotify:track:2Vc6NJ9PW9gD9q343XFRKx,https://api.spotify.com/v1/tracks/2Vc6NJ9PW9gD...,https://api.spotify.com/v1/audio-analysis/2Vc6...,124539,4,Dark Trap,Mercury: Retrograde,NaN,NaN
1,0.719,0.493,8,-7.230,1,0.0794,0.4010,0.000000,0.1180,0.1240,...,7pgJBLVz5VmnL7uGHmRj6p,spotify:track:7pgJBLVz5VmnL7uGHmRj6p,https://api.spotify.com/v1/tracks/7pgJBLVz5Vmn...,https://api.spotify.com/v1/audio-analysis/7pgJ...,224427,4,Dark Trap,Pathology,NaN,NaN
2,0.850,0.893,5,-4.783,1,0.0623,0.0138,0.000004,0.3720,0.0391,...,0vSWgAlfpye0WCGeNmuNhy,spotify:track:0vSWgAlfpye0WCGeNmuNhy,https://api.spotify.com/v1/tracks/0vSWgAlfpye0...,https://api.spotify.com/v1/audio-analysis/0vSW...,98821,4,Dark Trap,Symbiote,NaN,NaN
3,0.476,0.781,0,-4.710,1,0.1030,0.0237,0.000000,0.1140,0.1750,...,0VSXnJqQkwuH2ei1nOQ1nu,spotify:track:0VSXnJqQkwuH2ei1nOQ1nu,https://api.spotify.com/v1/tracks/0VSXnJqQkwuH...,https://api.spotify.com/v1/audio-analysis/0VSX...,123661,3,Dark Trap,ProductOfDrugs (Prod. The Virus and Antidote),NaN,NaN
4,0.798,0.624,2,-7.668,1,0.2930,0.2170,0.000000,0.1660,0.5910,...,4jCeguq9rMTlbMmPHuO7S3,spotify:track:4jCeguq9rMTlbMmPHuO7S3,https://api.spotify.com/v1/tracks/4jCeguq9rMTl...,https://api.spotify.com/v1/audio-analysis/4jCe...,123298,4,Dark Trap,Venom,NaN,NaN

In [4]:
display(df.describe())

,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,Unnamed: 0
count,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,42305.000000,20780.000000
mean,0.639364,0.762516,5.370240,-6.465442,0.549462,0.136561,0.096160,0.283048,0.214079,0.357101,147.474056,250865.846685,3.972580,10483.970645
std,0.156617,0.183823,3.666145,2.941165,0.497553,0.126168,0.170827,0.370791,0.175576,0.233200,23.844623,102957.713571,0.268342,6052.359519
min,0.065100,0.000243,0.000000,-33.357000,0.000000,0.022700,0.000001,0.000000,0.010700,0.018700,57.967000,25600.000000,1.000000,0.000000
25%,0.524000,0.632000,1.000000,-8.161000,0.000000,0.049100,0.001730,0.000000,0.099600,0.161000,129.931000,179840.000000,4.000000,5255.750000
50%,0.646000,0.803000,6.000000,-6.234000,1.000000,0.075500,0.016400,0.005940,0.135000,0.322000,144.973000,224760.000000,4.000000,10479.500000
75%,0.766000,0.923000,9.000000,-4.513000,1.000000,0.193000,0.107000,0.722000,0.294000,0.522000,161.464000,301133.000000,4.000000,15709.250000
max,0.988000,1.000000,11.000000,3.148000,1.000000,0.946000,0.988000,0.989000,0.988000,0.988000,220.290000,913052.000000,5.000000,20999.000000

In [5]:
print(df.dtypes)

danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
type                 object
id                   object
uri                  object
track_href           object
analysis_url         object
duration_ms           int64
time_signature        int64
genre                object
song_name            object
Unnamed: 0          float64
title                object
dtype: object

In [6]:
display((df.select_dtypes(include=["object"])).nunique())

type                1
id              35877
uri             35877
track_href      35877
analysis_url    35877
genre              15
song_name       15439
title             132
dtype: int64

In [7]:
print(df.isnull().sum())

danceability            0
energy                  0
key                     0
loudness                0
mode                    0
speechiness             0
acousticness            0
instrumentalness        0
liveness                0
valence                 0
tempo                   0
type                    0
id                      0
uri                     0
track_href              0
analysis_url            0
duration_ms             0
time_signature          0
genre                   0
song_name           20786
Unnamed: 0          21525
title               21525
dtype: int64

Vemos qué porcentaje representan los nulos en sus respectivas columnas.

In [8]:
print(df.isnull().sum()/df.shape[0]*100)

danceability         0.000000
energy               0.000000
key                  0.000000
loudness             0.000000
mode                 0.000000
speechiness          0.000000
acousticness         0.000000
instrumentalness     0.000000
liveness             0.000000
valence              0.000000
tempo                0.000000
type                 0.000000
id                   0.000000
uri                  0.000000
track_href           0.000000
analysis_url         0.000000
duration_ms          0.000000
time_signature       0.000000
genre                0.000000
song_name           49.133672
Unnamed: 0          50.880511
title               50.880511
dtype: float64

Vemos que la mitad son nulos. Podemos hacer varias cosas, eliminar las tres columnas o imputarlos. Voy a probar a borrar las columnas de 'song_name' y 'Unnamed: 0' y en 'title' reemplazar los nulos por una nueva categoría que sea 'unnamed'. También voy a eliminar las categorías 'id', 'uri', 'track_href', 'analysis_url' ya que no aportan al análisis. 

Por otro lado voy a escalar las variables numéricas usando la normalización Z-score, voy guardar un .csv que solo contenga las variables numéricas, otro que contenga las numéricas y las categóricas y otro que contenga ambas pero con las categóricas procesadas.

Voy a usar por un lado, One Hot Encoding y Laber Encoder, y guardarlo en dos csv distintos.

In [9]:
df.drop(columns=['Unnamed: 0', 'song_name', 'id', 'uri', 'track_href', 'analysis_url'], inplace=True)
df['title']=df['title'].fillna('unnamed')
df.reset_index(drop=True, inplace=True)

In [10]:
df_cat = df.select_dtypes(include='object')
df_num = df.select_dtypes(include='number')

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df_num_scaled = sc.fit_transform(df_num)
df_num = pd.DataFrame(df_num_scaled, columns=df_num.columns)
df_num.to_csv("genres_clean_num.csv", index=False)

In [12]:
df_comb = pd.concat([df_num, df_cat], axis=1)
df_comb.to_csv("genres_clean_comb.csv", index=False)

In [13]:
from sklearn.preprocessing import LabelEncoder
df_cat1 = pd.get_dummies(df_cat, columns=df_cat.columns, drop_first=False)
encoders = {}
for col in df_cat.columns:
    le = LabelEncoder()
    df_cat[col] = le.fit_transform(df_cat[col])
    encoders[col] = le
    df_cat2 = df_cat.copy()

df_comb1 = pd.concat([df_num, df_cat1], axis=1)
df_comb2 = pd.concat([df_num, df_cat2], axis=1)
df_comb1.to_csv("genres_clean_comb1.csv", index=False)
df_comb2.to_csv("genres_clean_comb2.csv", index=False)